== Android

Android has played a very important role on the Open Source community. It is a prime example of a real successful product that is based on open source – the Linux operating system, “open source” Java, and it has greatly contributed to both the Linux OS project and the Android project via the Open Handset Alliance. The result is enabling both enthutiasts as well as small-and-large 3rd-party vendors who takes advantage of the Android open source projects for their own personal projects, for research and academia, and/or own full-blown Products. 

Today, Android is the top open source project for mobile devices powering millions of mobile devices. But, it all started back in 2005, when a small, unknown at the time startup called Android Inc. was acquired by Google Inc. With Android, Google entered the mobile space. The talent-acquisition brought into Google their current employees including its co-founder and mobile technology visionary Andy Rubin who also had co-founded the successful Danger Inc., creators of the Sidekick. 

With the acquisition of Android Inc, Google entered the mobile space while promoting the spirit of open source. Later in 2007, together with other major companies, it created the Open Handset Alliance consortium with the goal of promoting Android as a standard for mobile platforms. Today Android has taken the mobile industry by surprise with major 3rd-party handset manufacturers and nework operators around the world embracing Android.  In addition, the Android ecoystem and developer community, both key elements of Android’s success, are very strong.

The future of Android looks bright. From smartphones to tablets to TVs, to home appliances and Machine-to-Machine (M2M), expect Android to power all of these, while grabbing a large segment of the mobile and embedded market. Expect Android entering the Emerging markets via low-cost, Android-powered handsets, extending the reach and business opportunities to all Android developers into markets in Africa and other emerging markets.

We have chosen a selection of popular books in this bibliography that span Android topics with the intent that you will be able to use it on your path. From basic Android core application concepts, the Java programming language on Android, to advanced topics that include advanced graphics, gaming and communications, we hope you will use these books to your advantage.
